// Airline Analytics Dashboard JS
// Author: Generated by AI

/* global Chart */

// ------------ COLOR PALETTE (chart.js fills) ------------
const COLOR_PALETTE = [
  '#1FB8CD', '#FFC185', '#B4413C', '#ECEBD5', '#5D878F',
  '#DB4545', '#D2BA4C', '#964325', '#944454', '#13343B'
];

// ------------ DATA (embedded) ------------
const data = {
  indianFinancial: {
    airlines: ["IndiGo", "Air India", "SpiceJet", "Akasa", "Others"],
    years: ["2020", "2021", "2022", "2023", "2024", "2025"],
    revenue: [
      [14641, 14641, 25931, 54446, 68904, 80803],
      [30927, 30927, 30927, 31377, 38812, 61000],
      [6364, 6364, 6364, 8572, 7050, 8000],
      [0, 0, 0, 778, 3144, 4680],
      [8500, 8500, 9000, 12000, 15000, 18000]
    ],
    profit: [
      [-5830, -5830, -6171, -317, 8167, 7253],
      [-20279, -20279, -20279, -11388, -4444, 2000],
      [-1725, -1030, -1744, -1513, -409, 500],
      [0, 0, 0, -745, -1670, -1200],
      [-2000, -2000, -1800, -1500, -800, 200]
    ],
    margin: [
      [0, 0, 2, 12, 24, 22],
      [-65.5, -65.5, -65.5, -36.3, -11.4, 3.3],
      [-27.1, -16.2, -27.4, -17.6, -5.8, 6.3],
      [0, 0, 0, -95.8, -53.1, -25.6],
      [-23.5, -23.5, -20.0, -12.5, -5.3, 1.1]
    ]
  },
  intlFinancial: {
    airlines: ["IndiGo", "Air India", "Qatar Airways", "Singapore Airlines", "Cathay Pacific", "Emirates", "ANA"],
    years: ["2020", "2021", "2022", "2023", "2024", "2025"],
    revenue: [
      [1950, 1950, 3457, 7258, 9177, 10777],
      [4120, 4120, 4120, 4185, 5172, 8130],
      [14400, 15500, 18700, 20900, 22200, 23600],
      [7800, 9200, 13400, 19000, 19500, 20400],
      [4300, 5100, 7800, 12900, 13600, 14500],
      [8500, 12300, 18200, 33000, 34900, 39600],
      [12800, 15400, 18900, 20600, 22600, 24500]
    ],
    profit: [
      [-777, -777, -822, -42, 1088, 967],
      [-2700, -2700, -2700, -1517, -592, 267],
      [-4100, -2800, 1540, 4400, 1670, 2100],
      [-2900, -1800, 2100, 2675, 2800, 3100],
      [-1800, -1200, -930, 1270, 1270, 1400],
      [-5500, -3200, 2900, 4700, 5800, 6200],
      [-3200, -2100, 1600, 1570, 1966, 2200]
    ],
    margin: [
      [-40, -40, 2, 12, 24, 22],
      [-65.5, -65.5, -65.5, -36.3, -11.4, 3.3],
      [-28.5, -18.1, 8.2, 21.1, 7.5, 8.9],
      [-37.2, -19.6, 15.7, 14.1, 14.4, 15.2],
      [-41.9, -23.5, -11.9, 9.8, 9.3, 9.7],
      [-64.7, -26.0, 15.9, 14.2, 16.6, 15.7],
      [-25.0, -13.6, 8.5, 7.6, 8.7, 9.0]
    ]
  },
  otp: {
    indian: {
      airlines: ["IndiGo", "Air India", "SpiceJet", "Akasa", "Others"],
      years: ["2020", "2021", "2022", "2023", "2024", "2025"],
      values: [
        [75.0, 77.0, 79.0, 77.5, 70.79, 91.3],
        [65.0, 67.0, 69.0, 72.8, 63.48, 81.0],
        [68.0, 70.0, 72.0, 62.0, 48.61, 57.1],
        [0, 0, 85.0, 78.2, 71.32, 89.2],
        [70.0, 72.0, 74.0, 76.0, 65.0, 75.0]
      ]
    },
    intl: {
      airlines: ["IndiGo", "Air India", "Qatar Airways", "Singapore Airlines", "Cathay Pacific", "Emirates", "ANA"],
      years: ["2020", "2021", "2022", "2023", "2024", "2025"],
      values: [
        [75.0, 77.0, 79.0, 77.5, 70.79, 91.3],
        [65.0, 67.0, 69.0, 72.8, 63.48, 81.0],
        [82.0, 84.0, 85.5, 87.0, 87.4, 87.4],
        [84.0, 85.0, 86.0, 87.5, 88.3, 88.3],
        [78.0, 80.0, 81.5, 83.0, 83.2, 83.2],
        [79.0, 81.0, 82.0, 83.5, 84.6, 84.6],
        [83.0, 84.0, 85.0, 86.0, 86.3, 86.3]
      ]
    }
  },
  customer: {
    indian: {
      airlines: ["IndiGo", "Air India", "SpiceJet", "Akasa", "Others"],
      nps23: [50, 25, -25, 35, 30],
      nps24: [45, 30, -11, 40, 32],
      csat24: [3.59, 3.43, 3.23, 3.8, 3.4],
      ces24: [65, 58, 52, 70, 60]
    },
    intl: {
      airlines: ["IndiGo", "Air India", "Qatar Airways", "Singapore Airlines", "Cathay Pacific", "Emirates", "ANA"],
      nps24: [45, 30, 39, 10, 44, 67, 65],
      csat24: [7.2, 6.8, 7.8, 9.9, 8.1, 9.0, 8.9],
      ces24: [65, 58, 74, 85, 78, 82, 80]
    }
  },
  safety: {
    labels: ["Global", "Asia-Pacific", "Middle East"],
    accidentRate: [1.13, 1.04, 1.08],
    fatalityRisk: [0.06, 0.15, 0.0]
  },
  environmental: {
    co2: {
      labels: ["2019", "2020", "2021", "2022", "2023", "2024"],
      indigo: [2.8, 2.9, 3.2, 3.8, 4.2, 4.8],
      air_india: [3.2, 3.0, 3.1, 3.5, 4.0, 5.5],
      spicejet: [1.2, 1.0, 1.1, 1.3, 1.4, 1.6],
      qatar: [8.5, 9.2, 11.8, 13.2, 14.1, 15.0],
      singapore: [7.2, 8.1, 10.5, 12.0, 12.8, 13.5],
      emirates: [12.5, 15.2, 18.9, 22.1, 24.6, 26.8]
    },
    saf: {
      labels: ["2019", "2020", "2021", "2022", "2023", "2024"],
      indigo: [0, 0, 0.1, 0.2, 0.3, 0.5],
      air_india: [0, 0, 0.1, 0.3, 0.5, 0.8],
      spicejet: [0.5, 0.3, 0.4, 0.6, 0.8, 1.0],
      qatar: [0.2, 0.4, 0.8, 1.2, 1.8, 2.5],
      singapore: [0.3, 0.5, 1.0, 1.5, 2.2, 3.0],
      emirates: [0.1, 0.3, 0.6, 1.0, 1.5, 2.2]
    }
  },
  employee: {
    attritionYears: ["2019", "2020", "2021", "2022", "2023", "2024"],
    attrition: {
      indigo: [8.5, 9.2, 10.1, 9.8, 8.9, 8.2],
      air_india: [12.5, 15.2, 14.8, 13.5, 12.1, 11.0],
      spicejet: [18.2, 22.1, 19.8, 16.5, 15.2, 14.0],
      akasa: [0, 0, 5.2, 8.5, 12.1, 10.8],
      qatar: [6.2, 7.1, 6.8, 6.5, 6.0, 5.8],
      singapore: [8.1, 12.5, 10.2, 8.8, 7.5, 7.0],
      emirates: [9.5, 15.8, 12.3, 10.1, 9.2, 8.5],
      ana: [7.8, 9.2, 8.5, 7.9, 7.2, 6.8]
    },
    satisfaction: {
      indigo: 72,
      air_india: 65,
      spicejet: 58,
      akasa: 78,
      qatar: 74,
      singapore: 82,
      emirates: 79,
      ana: 80
    }
  }
};

// Global chart storage
window.chartInstances = {};

// ------------ NAVIGATION ------------
document.addEventListener('DOMContentLoaded', function() {
  const navButtons = document.querySelectorAll('.nav-btn');
  
  navButtons.forEach(btn => {
    btn.addEventListener('click', function(e) {
      e.preventDefault();
      console.log('Tab clicked:', this.textContent);
      
      const targetId = this.getAttribute('data-target');
      console.log('Target ID:', targetId);
      
      // Hide all sections first
      const sections = document.querySelectorAll('.section');
      sections.forEach(section => {
        section.classList.add('hidden');
        console.log('Hidden section:', section.id);
      });
      
      // Show target section
      const targetSection = document.getElementById(targetId);
      if (targetSection) {
        targetSection.classList.remove('hidden');
        console.log('Showing section:', targetSection.id);
      } else {
        console.error('Target section not found:', targetId);
      }
      
      // Update active button
      navButtons.forEach(b => b.classList.remove('active'));
      this.classList.add('active');
      
      // Initialize international charts if needed
      if (targetId === 'international-section' && !window._intlChartsCreated) {
        console.log('Creating international charts...');
        setTimeout(() => {
          createInternationalCharts();
          window._intlChartsCreated = true;
          console.log('International charts created');
        }, 200);
      }
    });
  });
  
  // Initialize Indian charts on page load
  console.log('Initializing Indian charts...');
  createIndianCharts();
  console.log('Indian charts initialized');
});

// ------------ HELPER FUNCTIONS ------------
function createLineDatasets(labels, valuesArray) {
  return valuesArray.map((arr, idx) => ({
    label: labels[idx],
    data: arr,
    borderColor: COLOR_PALETTE[idx % COLOR_PALETTE.length],
    backgroundColor: COLOR_PALETTE[idx % COLOR_PALETTE.length],
    tension: 0.3,
    borderWidth: 2,
    pointRadius: 4,
    pointHoverRadius: 8,
    segment: {
      borderDash: ctx => ctx.p1DataIndex >= 4 ? [6, 6] : undefined
    }
  }));
}

function createBarDataset(label, dataArr, colorIdx) {
  return {
    label,
    data: dataArr,
    backgroundColor: COLOR_PALETTE[colorIdx % COLOR_PALETTE.length],
    borderColor: COLOR_PALETTE[colorIdx % COLOR_PALETTE.length],
    borderWidth: 1
  };
}

// ------------ TOOLTIP OPTIONS ------------
function getTooltipOptions(unitLabel) {
  return {
    enabled: true,
    mode: 'nearest',
    intersect: false,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    titleColor: '#ffffff',
    bodyColor: '#ffffff',
    borderColor: '#1FB8CD',
    borderWidth: 1,
    cornerRadius: 8,
    displayColors: true,
    callbacks: {
      label: function(context) {
        const value = context.parsed.y;
        const formattedValue = typeof value === 'number' ? value.toFixed(2) : value;
        return `${context.dataset.label}: ${formattedValue} ${unitLabel}`;
      },
      title: function(context) {
        return context[0].label;
      }
    }
  };
}

// ------------ INDIAN SECTION CHARTS ------------
function createIndianCharts() {
  console.log('Creating Indian financial charts...');
  
  // Revenue Trend
  const revenueCtx = document.getElementById('indianRevenueChart');
  if (revenueCtx) {
    window.chartInstances.indianRevenue = new Chart(revenueCtx, {
      type: 'line',
      data: {
        labels: data.indianFinancial.years,
        datasets: createLineDatasets(data.indianFinancial.airlines, data.indianFinancial.revenue)
      },
      options: commonLineOptions('₹ Crore')
    });
  }

  // Profit Trend
  const profitCtx = document.getElementById('indianProfitChart');
  if (profitCtx) {
    window.chartInstances.indianProfit = new Chart(profitCtx, {
      type: 'line',
      data: {
        labels: data.indianFinancial.years,
        datasets: createLineDatasets(data.indianFinancial.airlines, data.indianFinancial.profit)
      },
      options: commonLineOptions('₹ Crore')
    });
  }

  // Margin Trend
  const marginCtx = document.getElementById('indianMarginChart');
  if (marginCtx) {
    window.chartInstances.indianMargin = new Chart(marginCtx, {
      type: 'line',
      data: {
        labels: data.indianFinancial.years,
        datasets: createLineDatasets(data.indianFinancial.airlines, data.indianFinancial.margin)
      },
      options: commonLineOptions('%')
    });
  }

  // OTP
  const otpCtx = document.getElementById('indianOtpChart');
  if (otpCtx) {
    window.chartInstances.indianOtp = new Chart(otpCtx, {
      type: 'line',
      data: {
        labels: data.otp.indian.years,
        datasets: createLineDatasets(data.otp.indian.airlines, data.otp.indian.values)
      },
      options: commonLineOptions('%')
    });
  }

  // Customer Satisfaction - NPS
  const npsCtx = document.getElementById('indianNpsChart');
  if (npsCtx) {
    window.chartInstances.indianNps = new Chart(npsCtx, {
      type: 'bar',
      data: {
        labels: data.customer.indian.airlines,
        datasets: [
          createBarDataset('2023', data.customer.indian.nps23, 0),
          createBarDataset('2024', data.customer.indian.nps24, 1)
        ]
      },
      options: commonBarOptions('NPS Score')
    });
  }

  // CSAT
  const csatCtx = document.getElementById('indianCsatChart');
  if (csatCtx) {
    window.chartInstances.indianCsat = new Chart(csatCtx, {
      type: 'bar',
      data: {
        labels: data.customer.indian.airlines,
        datasets: [createBarDataset('CSAT 2024', data.customer.indian.csat24, 2)]
      },
      options: commonBarOptions('CSAT Score')
    });
  }

  // CES
  const cesCtx = document.getElementById('indianCesChart');
  if (cesCtx) {
    window.chartInstances.indianCes = new Chart(cesCtx, {
      type: 'bar',
      data: {
        labels: data.customer.indian.airlines,
        datasets: [createBarDataset('CES 2024', data.customer.indian.ces24, 3)]
      },
      options: commonBarOptions('CES Score')
    });
  }

  // Safety
  const safetyCtx = document.getElementById('safetyChart');
  if (safetyCtx) {
    window.chartInstances.safety = new Chart(safetyCtx, {
      type: 'bar',
      data: {
        labels: data.safety.labels,
        datasets: [
          {
            label: 'All Accident Rate',
            data: data.safety.accidentRate,
            backgroundColor: COLOR_PALETTE[4],
            yAxisID: 'y1'
          },
          {
            label: 'Fatality Risk',
            data: data.safety.fatalityRisk,
            backgroundColor: COLOR_PALETTE[5],
            yAxisID: 'y2'
          }
        ]
      },
      options: safetyChartOptions()
    });
  }

  // Environmental: CO2
  const co2Ctx = document.getElementById('indianCo2Chart');
  if (co2Ctx) {
    window.chartInstances.indianCo2 = new Chart(co2Ctx, {
      type: 'line',
      data: {
        labels: data.environmental.co2.labels,
        datasets: [
          lineDS('IndiGo', data.environmental.co2.indigo, 0),
          lineDS('Air India', data.environmental.co2.air_india, 1),
          lineDS('SpiceJet', data.environmental.co2.spicejet, 2)
        ]
      },
      options: commonLineOptions('Million Tonnes')
    });
  }

  // SAF Usage
  const safCtx = document.getElementById('indianSafChart');
  if (safCtx) {
    window.chartInstances.indianSaf = new Chart(safCtx, {
      type: 'line',
      data: {
        labels: data.environmental.saf.labels,
        datasets: [
          lineDS('IndiGo', data.environmental.saf.indigo, 0),
          lineDS('Air India', data.environmental.saf.air_india, 1),
          lineDS('SpiceJet', data.environmental.saf.spicejet, 2)
        ]
      },
      options: commonLineOptions('%')
    });
  }

  // Employee Attrition
  const attritionCtx = document.getElementById('indianAttritionChart');
  if (attritionCtx) {
    window.chartInstances.indianAttrition = new Chart(attritionCtx, {
      type: 'line',
      data: {
        labels: data.employee.attritionYears,
        datasets: [
          lineDS('IndiGo', data.employee.attrition.indigo, 0),
          lineDS('Air India', data.employee.attrition.air_india, 1),
          lineDS('SpiceJet', data.employee.attrition.spicejet, 2),
          lineDS('Akasa', data.employee.attrition.akasa, 3)
        ]
      },
      options: commonLineOptions('%')
    });
  }

  // Employee Satisfaction
  const empSatCtx = document.getElementById('indianEmpSatChart');
  if (empSatCtx) {
    window.chartInstances.indianEmpSat = new Chart(empSatCtx, {
      type: 'bar',
      data: {
        labels: ['IndiGo', 'Air India', 'SpiceJet', 'Akasa'],
        datasets: [createBarDataset('Employee Satisfaction', [
          data.employee.satisfaction.indigo,
          data.employee.satisfaction.air_india,
          data.employee.satisfaction.spicejet,
          data.employee.satisfaction.akasa
        ], 4)]
      },
      options: commonBarOptions('Satisfaction Index')
    });
  }
  
  console.log('Indian charts creation completed');
}

// ------------ INTERNATIONAL CHARTS ------------
function createInternationalCharts() {
  console.log('Creating International charts...');
  
  // Revenue Trend
  const revenueCtx = document.getElementById('intlRevenueChart');
  if (revenueCtx) {
    window.chartInstances.intlRevenue = new Chart(revenueCtx, {
      type: 'line',
      data: {
        labels: data.intlFinancial.years,
        datasets: createLineDatasets(data.intlFinancial.airlines, data.intlFinancial.revenue)
      },
      options: commonLineOptions('US$ Million')
    });
  }

  // Profit
  const profitCtx = document.getElementById('intlProfitChart');
  if (profitCtx) {
    window.chartInstances.intlProfit = new Chart(profitCtx, {
      type: 'line',
      data: {
        labels: data.intlFinancial.years,
        datasets: createLineDatasets(data.intlFinancial.airlines, data.intlFinancial.profit)
      },
      options: commonLineOptions('US$ Million')
    });
  }

  // Margin
  const marginCtx = document.getElementById('intlMarginChart');
  if (marginCtx) {
    window.chartInstances.intlMargin = new Chart(marginCtx, {
      type: 'line',
      data: {
        labels: data.intlFinancial.years,
        datasets: createLineDatasets(data.intlFinancial.airlines, data.intlFinancial.margin)
      },
      options: commonLineOptions('%')
    });
  }

  // OTP
  const otpCtx = document.getElementById('intlOtpChart');
  if (otpCtx) {
    window.chartInstances.intlOtp = new Chart(otpCtx, {
      type: 'line',
      data: {
        labels: data.otp.intl.years,
        datasets: createLineDatasets(data.otp.intl.airlines, data.otp.intl.values)
      },
      options: commonLineOptions('%')
    });
  }

  // Customer NPS
  const npsCtx = document.getElementById('intlNpsChart');
  if (npsCtx) {
    window.chartInstances.intlNps = new Chart(npsCtx, {
      type: 'bar',
      data: {
        labels: data.customer.intl.airlines,
        datasets: [createBarDataset('NPS 2024', data.customer.intl.nps24, 5)]
      },
      options: commonBarOptions('NPS Score')
    });
  }

  // CSAT
  const csatCtx = document.getElementById('intlCsatChart');
  if (csatCtx) {
    window.chartInstances.intlCsat = new Chart(csatCtx, {
      type: 'bar',
      data: {
        labels: data.customer.intl.airlines,
        datasets: [createBarDataset('CSAT 2024', data.customer.intl.csat24, 6)]
      },
      options: commonBarOptions('CSAT Score')
    });
  }

  // CES
  const cesCtx = document.getElementById('intlCesChart');
  if (cesCtx) {
    window.chartInstances.intlCes = new Chart(cesCtx, {
      type: 'bar',
      data: {
        labels: data.customer.intl.airlines,
        datasets: [createBarDataset('CES 2024', data.customer.intl.ces24, 7)]
      },
      options: commonBarOptions('CES Score')
    });
  }

  // Safety Chart for International
  const safetyCtx = document.getElementById('safetyChartIntl');
  if (safetyCtx) {
    window.chartInstances.safetyIntl = new Chart(safetyCtx, {
      type: 'bar',
      data: {
        labels: data.safety.labels,
        datasets: [
          {
            label: 'All Accident Rate',
            data: data.safety.accidentRate,
            backgroundColor: COLOR_PALETTE[4],
            yAxisID: 'y1'
          },
          {
            label: 'Fatality Risk',
            data: data.safety.fatalityRisk,
            backgroundColor: COLOR_PALETTE[5],
            yAxisID: 'y2'
          }
        ]
      },
      options: safetyChartOptions()
    });
  }

  // CO2 (International airlines subset)
  const co2Ctx = document.getElementById('intlCo2Chart');
  if (co2Ctx) {
    window.chartInstances.intlCo2 = new Chart(co2Ctx, {
      type: 'line',
      data: {
        labels: data.environmental.co2.labels,
        datasets: [
          lineDS('IndiGo', data.environmental.co2.indigo, 0),
          lineDS('Air India', data.environmental.co2.air_india, 1),
          lineDS('Qatar Airways', data.environmental.co2.qatar, 2),
          lineDS('Singapore Airlines', data.environmental.co2.singapore, 3),
          lineDS('Emirates', data.environmental.co2.emirates, 4)
        ]
      },
      options: commonLineOptions('Million Tonnes')
    });
  }

  // SAF Usage
  const safCtx = document.getElementById('intlSafChart');
  if (safCtx) {
    window.chartInstances.intlSaf = new Chart(safCtx, {
      type: 'line',
      data: {
        labels: data.environmental.saf.labels,
        datasets: [
          lineDS('IndiGo', data.environmental.saf.indigo, 0),
          lineDS('Air India', data.environmental.saf.air_india, 1),
          lineDS('Qatar Airways', data.environmental.saf.qatar, 2),
          lineDS('Singapore Airlines', data.environmental.saf.singapore, 3),
          lineDS('Emirates', data.environmental.saf.emirates, 4)
        ]
      },
      options: commonLineOptions('%')
    });
  }

  // Attrition (International subset)
  const attritionCtx = document.getElementById('intlAttritionChart');
  if (attritionCtx) {
    window.chartInstances.intlAttrition = new Chart(attritionCtx, {
      type: 'line',
      data: {
        labels: data.employee.attritionYears,
        datasets: [
          lineDS('IndiGo', data.employee.attrition.indigo, 0),
          lineDS('Air India', data.employee.attrition.air_india, 1),
          lineDS('Qatar Airways', data.employee.attrition.qatar, 2),
          lineDS('Singapore Airlines', data.employee.attrition.singapore, 3),
          lineDS('Emirates', data.employee.attrition.emirates, 4),
          lineDS('ANA', data.employee.attrition.ana, 5)
        ]
      },
      options: commonLineOptions('%')
    });
  }

  // Employee Satisfaction Intl
  const empSatCtx = document.getElementById('intlEmpSatChart');
  if (empSatCtx) {
    window.chartInstances.intlEmpSat = new Chart(empSatCtx, {
      type: 'bar',
      data: {
        labels: ['IndiGo', 'Air India', 'Qatar Airways', 'Singapore Airlines', 'Emirates', 'ANA'],
        datasets: [createBarDataset('Employee Satisfaction', [
          data.employee.satisfaction.indigo,
          data.employee.satisfaction.air_india,
          data.employee.satisfaction.qatar,
          data.employee.satisfaction.singapore,
          data.employee.satisfaction.emirates,
          data.employee.satisfaction.ana
        ], 8)]
      },
      options: commonBarOptions('Satisfaction Index')
    });
  }
  
  console.log('International charts creation completed');
}

// ------------ OPTIONS HELPERS ------------
function commonLineOptions(unitLabel) {
  return {
    responsive: true,
    maintainAspectRatio: false,
    interaction: { 
      mode: 'point', 
      intersect: false 
    },
    plugins: {
      tooltip: getTooltipOptions(unitLabel),
      legend: {
        position: 'bottom',
        labels: { boxWidth: 18, padding: 16 }
      }
    },
    scales: {
      x: { grid: { display: false } },
      y: { 
        ticks: { 
          callback: function(value) {
            return value + ' ' + unitLabel;
          }
        } 
      }
    }
  };
}

function commonBarOptions(unitLabel) {
  return {
    responsive: true,
    maintainAspectRatio: false,
    interaction: { mode: 'nearest', intersect: false },
    plugins: {
      tooltip: getTooltipOptions(unitLabel || ''),
      legend: { position: 'bottom' }
    }
  };
}

function safetyChartOptions() {
  return {
    responsive: true,
    maintainAspectRatio: false,
    interaction: { mode: 'nearest', intersect: false },
    plugins: {
      tooltip: {
        enabled: true,
        mode: 'nearest',
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        titleColor: '#ffffff',
        bodyColor: '#ffffff',
        borderColor: '#1FB8CD',
        borderWidth: 1,
        cornerRadius: 8,
        callbacks: {
          label: function(context) {
            return context.dataset.label + ': ' + context.parsed.y;
          }
        }
      },
      legend: { position: 'bottom' }
    },
    scales: {
      y1: {
        position: 'left',
        title: { display: true, text: 'Accident Rate (per million flights)' }
      },
      y2: {
        position: 'right',
        grid: { drawOnChartArea: false },
        title: { display: true, text: 'Fatality Risk' }
      }
    }
  };
}

function lineDS(label, dataArr, colorIdx) {
  return {
    label,
    data: dataArr,
    borderColor: COLOR_PALETTE[colorIdx % COLOR_PALETTE.length],
    backgroundColor: COLOR_PALETTE[colorIdx % COLOR_PALETTE.length],
    tension: 0.35,
    borderWidth: 2,
    pointRadius: 4,
    pointHoverRadius: 8,
    segment: {
      borderDash: ctx => ctx.p1DataIndex >= (dataArr.length - 2) ? [6, 6] : undefined
    }
  };
}
